### ISSUE TITLE
Include User-Limits in the User-Response

### ISSUE THREAD

**Issue by Nerixyz** [SevenTV/ServerGo#10]
Currently, the emote limit per user can be configured per instance by `limits.meta.channel_emote_slots`. However, this is never exposed to the users. Also the web-interface blindly assumes [200 max-emotes](https://github.com/SevenTV/App/blob/master/src/app/user/user-home/user-home.component.html#L5) per user although an instance could specify different limits.

The limits could be included in the user-response or some other response, possibly about the general instance.

**Comment by AnatoleAM** [comment]
This has been implemented in the GQL API as `emote_slots` in the User type. Is this something people would like to utilize in REST?

**Comment by Nerixyz** [comment]
Thanks! I don't need the limits in the REST API.
